In [17]:
import numpy as np;

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[8]

8

In [21]:
arr[1:5]

array([1, 2, 3, 4])

In [22]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [23]:
arr[1:5] = 100

In [24]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr=np.arange(0,11)

In [26]:
slice_of_arr=arr[0:5]

### This will broadcast. They are pointing to same memory addresses.

In [27]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [28]:
type(slice_of_arr)

numpy.ndarray

In [29]:
slice_of_arr[:]=99

### There will be changes in original array as well.

In [30]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Copying

In [31]:
slice_of_arr=arr[0:5].copy()

In [32]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [33]:
slice_of_arr[:]=100

In [34]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
slice_of_arr

array([100, 100, 100, 100, 100])

### There are no changes in original array.

## Comparision

In [37]:
arr=np.arange(1, 11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### This piece of code will generate a boolean array.

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

### Here the indices with value greater than 4 are marked true and rest false.

In [43]:
bool_arr=arr>4

In [44]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

### This will return values whose indices have value as true in bool_arr.

#### This can also be done as.

In [46]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])