In [26]:
import numpy as np

### Getting values in range. End not included

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Multiples of 3 the last parameter

In [28]:
np.arange(0,10, 3)

array([0, 3, 6, 9])

### Getting Zeros only.

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### Getting a number of values from range with equal difference between adjs.

In [30]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### For identity Matrix

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### For Random values.

In [36]:
np.random.rand(4,3)

array([[0.05322216, 0.10348981, 0.21423438],
       [0.27832429, 0.80651185, 0.90722541],
       [0.15137625, 0.39762266, 0.46996955],
       [0.24477009, 0.9577572 , 0.2363076 ]])

In [37]:
np.random.randn(10)

array([ 0.65510181, -0.46305858,  0.5791066 ,  0.28958256,  2.2319597 ,
       -0.38608404,  0.1119122 ,  0.35378335, -0.02235916,  0.97716617])

In [46]:
np.random.randint(5,74544,3)

array([51072, 11713,   154])

In [47]:
np.random.randint(5,74544,(4,5))

array([[ 3086, 10047, 18956, 64951, 19412],
       [40867, 60936, 36032, 39588, 30324],
       [47033, 36803, 64926, 68916,  7401],
       [51216, 45926, 20830, 43008, 17825]])

### Seeding

In [49]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [50]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [56]:
arr=np.arange(0,27)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [59]:
arr=arr.reshape(3,3,3)

In [60]:
arr.shape

(3, 3, 3)