In [1]:
import numpy as np;

In [3]:
arr=np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### For this to work both array should have same size.

In [10]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr^arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

### IMP: NumPy will not give zero in case of division by zero.

In [14]:
arr / arr

C:\Users\agraw\envs\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
1/arr

C:\Users\agraw\envs\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [16]:
arr.sum()

45